/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./src/App.vue')['default']
    Dialog: typeof import('./src/shared/ui/dialog/Dialog.vue')['default']
    Drawer: typeof import('./src/shared/ui/drawer/Drawer.vue')['default']
    EimzoModal: typeof import('./src/features/eimzo-modal/ui/EimzoModal.vue')['default']
    Footer: typeof import('./src/widgets/footer/ui/Footer.vue')['default']
    Header: typeof import('./src/widgets/header/ui/Header.vue')['default']
    Icon: typeof import('./src/shared/ui/icon/Icon.vue')['default']
    IconMdiClose: typeof import('~icons/mdi/close')['default']
    IconMdiKeyboardArrowDown: typeof import('~icons/mdi/keyboard-arrow-down')['default']
    LoginForm: typeof import('./src/features/login-form/ui/LoginForm.vue')['default']
    LoginFormWithUniversal: typeof import('./src/features/login-form/ui/LoginFormWithUniversal.vue')['default']
    LoginPage: typeof import('./src/pages/login/ui/LoginPage.vue')['default']
    Logo: typeof import('./src/shared/ui/logo/Logo.vue')['default']
    MainLayout: typeof import('./src/app/layouts/MainLayout.vue')['default']
    Profile: typeof import('./src/widgets/profile/ui/Profile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
